Добавил линтер, перевел go в версию 1.22
VanGoghDev/gophermart pull request #1
Opened 2024-06-28 17:50 UTC by VanGoghDev

2024-07-25 00:13 UTC, s-shpak requested changes
1. Большие запросы/ответы надо сжимать/разжимать (если это позволят автотесты)
2. Кажется, что в БД стоит создать индексы

2024-07-25 00:13 UTC, s-shpak commented on SPECIFICATION.md
> +* `POST /api/user/ttt` — регистрация пользователя;
Наверное, надо вернуть `register` здесь

2024-07-25 00:13 UTC, s-shpak commented on cmd/gophermart/main.go
> +	err = s.RunMigrations(cfg.DSN)
Инициализация стора и все смежные операции лучше инкапсулировать в отдельную функцию

2024-07-25 00:13 UTC, s-shpak commented on cmd/gophermart/main.go
> +	s, err := storage.New(ctx, slog, cfg.DSN)
Соединение к БД также надо закрывать при `graceful shutdown`

2024-07-25 00:13 UTC, s-shpak commented on cmd/gophermart/main.go
> +	var wg sync.WaitGroup
Во второй части курса мы разберем почему, но примитивы из пакета `sync` лучше всегда использовать через указатели

2024-07-25 00:13 UTC, s-shpak commented on internal/handlers/auth/register/register.go
> +func New(log *slog.Logger, s Register, secret string, tokenExpires time.Duration) http.HandlerFunc {
Кажется, что логика `Register` во многом дублирует логику `Login`, может, их можно как-то объединить ?

2024-07-25 00:13 UTC, s-shpak commented on internal/handlers/auth/register/register_test.go
> +			m.EXPECT().RegisterUser(gomock.Any(), gomock.Any(), gomock.Any()).
А почему бы с помощью мока не проверить, что приходит на вход ?

2024-07-25 00:13 UTC, s-shpak commented on internal/handlers/balance/getbalance/getbalance.go
> +			w.WriteHeader(http.StatusInternalServerError)
Внутренние ошибки надо логировать

2024-07-25 00:13 UTC, s-shpak commented on internal/handlers/orders/getorders/getorders.go
> +			w.WriteHeader(http.StatusInternalServerError)
Аналогично предыдущему и в других случаях тоже

2024-07-25 00:13 UTC, s-shpak commented on internal/middleware/auth/auth.go
> +type contextKey string
Лучше делать это не при помощи строки, а так: https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint

2024-07-25 00:13 UTC, s-shpak commented on internal/services/accrual/client/client.go
> +func (c *Client) GetAccrual(ctx context.Context, orderNum string) (order models.Accrual, err error) {
`accrual` может прислать `Too many requests`, что тогда стоит сделать ?

2024-07-25 00:13 UTC, s-shpak commented on internal/storage/migrations/000001_create_users_table.up.sql
> +    login TEXT PRIMARY KEY,
Не пользуйся `TEXT` без необходимости, лучше используй `VARCHAR`: https://brandur.org/text

2024-07-25 00:13 UTC, s-shpak commented on internal/storage/storage.go
> +	"github.com/lib/pq"
А зачем использовать еще и `pq`? Это устаревшая библиотека, не используй ее в новых проектах

2024-07-25 11:34 UTC, s-shpak requested changes

2024-07-25 11:34 UTC, s-shpak commented on internal/storage/migrations/000002_create_orders_table.up.sql
> +CREATE TABLE IF NOT EXISTS orders (
Миграции надо оборачивать в траназакции

2024-07-25 11:34 UTC, s-shpak commented on internal/storage/storage.go
> +		var pgErr *pq.Error
https://github.com/jackc/pgx/wiki/Error-Handling

2024-07-25 11:34 UTC, s-shpak commented on internal/storage/storage.go
> +			if pgErr.Code == "23505" {
https://github.com/jackc/pgerrcode

2024-07-25 11:34 UTC, s-shpak commented on internal/storage/storage.go
> +				return "", ErrAlreadyExists
Добавь контекст к этой ошибке:

```go
fmt.Errorf("%w: user with login %s exists", ErrAlreadyExists, login)
```

2024-07-25 11:34 UTC, s-shpak commented on internal/storage/storage.go
> +	err = tx.QueryRow(ctx, "SELECT balance FROM users WHERE login = $1", userLogin).
Попробуй переписать с использованием джоинов или CTE: https://www.postgresql.org/docs/current/queries-with.html

2024-07-25 11:34 UTC, s-shpak commented on internal/services/accrual/accrual.go
> +	rateLimit := 5
Это можно параметризовать

2024-07-31 11:37 UTC, s-shpak commented on internal/services/accrual/client/client.go
> +func (c *Client) GetAccrual(ctx context.Context, orderNum string) (order models.Accrual, err error) {
1. Необходимо делать `n` запросов к `accrual`
2. См. обсуждение про Too Many Requests

2024-08-01 20:28 UTC, VanGoghDev commented
Не знаю, как по мне красиво получилось)
Я проблему о том, что горутина может успеть прочитать два timestamp из одного канала, решил через мапу.

2024-08-01 21:50 UTC, s-shpak approved these changes

2024-08-02 11:38 UTC, merged